version: "3.7"
services:

  model-runner:
    image: ghcr.io/covid-policy-modelling/model-runner/model-runner:${RUNNER_VERSION:-master}
    environment:
      - GITHUB_RUN_ID
      - API_SHARED_SECRET
      - AZURE_STORAGE_ACCOUNT
      - AZURE_STORAGE_CONTAINER
      - AZURE_STORAGE_KEY
      - DOCKER_USER
      - DOCKER_PASSWORD
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./input:/data/input:rw"
      - "./output:/data/output:rw"
      - "./log:/data/log:rw"
    command: /data/input/runnerInputFile.json
