# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: test-run-simulation

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - run: echo "${{toJson(github.event.client_payload)}}"
